services:
  our-story-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "0.0.0.0:7000:7000"
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: production
      PORT: "7000"
      TRUST_PROXY: "1"
